/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * 
 * This file is automatically generated from:
 * ../cloudwatchlive/backend/lambda/createCognitoUser.ts
 * 
 * To make changes, edit the source TypeScript file and run the build.
 * 
 * Generated: 2025-10-08T23:57:56.180Z
 */

"use strict";var u=Object.defineProperty;var p=Object.getOwnPropertyDescriptor;var N=Object.getOwnPropertyNames;var h=Object.prototype.hasOwnProperty;var S=(r,e)=>{for(var s in e)u(r,s,{get:e[s],enumerable:!0})},f=(r,e,s,a)=>{if(e&&typeof e=="object"||typeof e=="function")for(let n of N(e))!h.call(r,n)&&n!==s&&u(r,n,{get:()=>e[n],enumerable:!(a=p(e,n))||a.enumerable});return r};var I=r=>f(u({},"__esModule",{value:!0}),r);var R={};S(R,{handler:()=>P});module.exports=I(R);var o=require("@aws-sdk/client-cognito-identity-provider"),l=new o.CognitoIdentityProviderClient({region:process.env.AWS_REGION||"ap-southeast-2"}),g=process.env.USER_POOL_ID,P=async r=>{if(console.log("Creating Cognito user with event:",JSON.stringify(r)),!g)throw new Error("USER_POOL_ID environment variable not set");let{userEmail:e,userFirstName:s,userLastName:a,userPhone:n,userRole:c,organizationId:U,sendWelcomeEmail:C}=r;try{let t=new o.AdminCreateUserCommand({UserPoolId:g,Username:e,UserAttributes:[{Name:"email",Value:e},{Name:"email_verified",Value:"true"},{Name:"given_name",Value:s},{Name:"family_name",Value:a},...n?[{Name:"phone_number",Value:n}]:[],{Name:"custom:organizationId",Value:U}],DesiredDeliveryMediums:["EMAIL"],MessageAction:C?o.MessageActionType.RESEND:o.MessageActionType.SUPPRESS}),i=await l.send(t);if(!i.User?.Username)throw new Error("Failed to create Cognito user - no username returned");let m=i.User.Attributes?.find(w=>w.Name==="sub")?.Value;if(!m)throw new Error("Failed to get Cognito sub from created user");console.log(`Cognito user created with sub: ${m}`);let d=c,E=new o.AdminAddUserToGroupCommand({UserPoolId:g,Username:e,GroupName:d});return await l.send(E),console.log(`User added to group: ${d}`),{cognitoSub:m,username:i.User.Username,userCreated:new Date().toISOString()}}catch(t){throw console.error("Error creating Cognito user:",t),t.name==="UsernameExistsException"?new Error(`User with email ${e} already exists in Cognito`):t}};0&&(module.exports={handler});
