AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Example S3 Resources"

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    AllowedPattern: ^[a-zA-Z0-9-]+$
  KMSKeyId:
    Type: String
    Description: KMS Key ID for bucket encryption (optional)
    Default: ""
  AppName:
    Type: String
    Description: Application short name used in resource naming (e.g., awse)

Resources:
  # S3 Bucket for storing nextjs/react app
  AWSEBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "nlmonorepo-${AppName}-userfiles-${Stage}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasKMSKey, aws:kms, AES256]
              KMSMasterKeyID:
                !If [HasKMSKey, !Ref KMSKeyId, !Ref "AWS::NoValue"]
            BucketKeyEnabled: true

Conditions:
  HasKMSKey: !Not [!Equals [!Ref KMSKeyId, ""]]

Outputs:
  BucketName:
    Value: !Ref AWSEBucket
    Description: Name of the application bucket
    Export:
      BucketName:
        Value: !Ref AWSEBucket
        Description: Name of the application S3 bucket

      BucketArn:
        Value: !GetAtt AWSEBucket.Arn
        Description: ARN of the application S3 bucket

      BucketRegionalDomainName:
        Value: !GetAtt AWSEBucket.RegionalDomainName
        Description: Regional domain name of the application S3 bucket
