AWSTemplateFormatVersion: '2010-09-09'
Description: 'Shared AWS resources for NL applications'

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    AllowedPattern: ^[a-zA-Z0-9-]+$
  TemplatesBucketName:
    Type: String
    Description: Name of the S3 bucket containing nested stack templates

Resources:
  KMSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/resources/KMS/KMS.yaml
      Parameters:
        Stage: !Ref Stage

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/resources/VPC/VPC.yaml
      Parameters:
        Stage: !Ref Stage

Outputs:
  SharedSecurityGroupFromVPCId:
    Value: !GetAtt VPCStack.Outputs.cwlSecurityGroupFromSharedVPCId
    Export:
      Name: !Sub SharedSecurityGroupFromVPCId-${Stage}

  SharedSecurityGroupFromVPC:
    Value: !GetAtt VPCStack.Outputs.cwlSecurityGroupFromSharedVPC
    Export:
      Name: !Sub SharedSecurityGroupFromVPC-${Stage}
          
  SharedKMSKey:
    Value: !GetAtt KMSStack.Outputs.cwlKMSKey
    Export:
      Name: !Sub SharedKMSKey-${Stage}

  SharedKMSKeyArn:
    Value: !GetAtt KMSStack.Outputs.cwlKMSKeyArn
    Export:
      Name: !Sub SharedKMSKeyArn-${Stage}