AWSTemplateFormatVersion: '2010-09-09'
Description: 'Shared AWS resources for NL applications'

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    AllowedPattern: ^[a-zA-Z0-9-]+$
  TemplatesBucketName:
    Type: String
    Description: Name of the S3 bucket containing nested stack templates

Resources:
  KMSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/resources/KMS/KMS.yaml
      Parameters:
        Stage: !Ref Stage

  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplatesBucketName}.s3.${AWS::Region}.amazonaws.com/resources/VPC/VPC.yaml
      Parameters:
        Stage: !Ref Stage

Outputs:
  SharedSecurityGroupFromVPCId:
    Value: !GetAtt VPCStack.Outputs.SharedSecurityGroupFromVPCId
    Export:
      Name: !Sub SharedSecurityGroupFromVPCId-${Stage}

  SharedSecurityGroupFromVPC:
    Value: !GetAtt VPCStack.Outputs.SharedSecurityGroupFromVPC
    Export:
      Name: !Sub SharedSecurityGroupFromVPC-${Stage}
          
  SharedKMSKey:
    Value: !GetAtt KMSStack.Outputs.SharedKMSKey
    Export:
      Name: !Sub SharedKMSKey-${Stage}

  SharedKMSKeyArn:
    Value: !GetAtt KMSStack.Outputs.SharedKMSKeyArn
    Export:
      Name: !Sub SharedKMSKeyArn-${Stage}

  KMSKeyId:
    Value: !GetAtt KMSStack.Outputs.SharedKMSKey
    Description: KMS Key ID for encryption
    Export:
      Name: !Sub KMSKeyId-${Stage}

  KMSKeyArn:
    Value: !GetAtt KMSStack.Outputs.SharedKMSKeyArn
    Description: KMS Key ARN
    Export:
      Name: !Sub KMSKeyArn-${Stage}

  VPCID:
    Value: !GetAtt VPCStack.Outputs.SharedVPCId
    Description: VPC ID
    Export:
      Name: !Sub VPCID-${Stage}

  TemplateBucketName:
    Value: !Ref TemplatesBucketName
    Export:
      Name: !Sub TemplateBucketName-${Stage}