org: vesnathan
app: nl-mono-repo
service: aws-shared-resources

configValidationMode: error

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-2
  stage: ${opt:stage}
  httpApi:
    cors: true
  vpc:
    securityGroupIds:
      - !GetAtt cwlSecurityGroupFromSharedVPC.GroupId
    subnetIds:
      - !ImportValue sharedSubnet1-${opt:stage}
      - !ImportValue sharedSubnet2-${opt:stage}
  environment:
    STAGE: ${opt:stage}

package:
  individually: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-prune-plugin

resources:
  - Resources:
  - ${file(./resources/DynamoDb/dynamoDb.yaml)}
  - ${file(./resources/Cognito/cognito.yaml)}
  - ${file(./resources/S3/s3.yaml)}
  - ${file(./resources/VPC/VPC.yaml)}
  - ${file(./resources/KMS/KMS.yaml)}
  # cloud formation outputs. The values can be referenced by other serverless.yml using !ImportValue <Export.Name>
  - Outputs:
      cwlSecurityGroupFromSharedVPCId:
        Value: !GetAtt cwlSecurityGroupFromSharedVPC.GroupId
        Export:
          Name: cwlSecurityGroupFromSharedVPCId-${opt:stage}

      cwlSecurityGroupFromSharedVPC: 
        Value: !Ref cwlSecurityGroupFromSharedVPC
        Export:
          Name: cwlSecurityGroupFromSharedVPC-${opt:stage}
          
      cwlKMSKey:
        Value: !Ref cwlKMSKey
        Export:
          Name: cwlKMSKey-${opt:stage}

      cwlKMSKeyArn:
        Value: !GetAtt cwlKMSKey.Arn
        Export:
          Name: cwlKMSKeyArn-${opt:stage}

