# Yarn Configuration
# This monorepo uses Yarn as the package manager
# All AI agents should use yarn commands instead of npm

nodeLinker: node-modules
enableGlobalCache: false
compressionLevel: mixed

# Workspace configuration
enableWorkspaces: true

# Network configuration
networkTimeout: 300000
httpTimeout: 300000
