projects:
  Backend Codegen Project:
    schemaPath: combined_schema.graphql
    includes:
      - GetawsbUser.graphql
    excludes:
      - ./amplify/**
      # - types/gqlTypes.ts (no longer used)
    extensions:
      amplify:
        codeGenTarget: typescript
        # generatedFileName: types/gqlTypes.ts (no longer used)
        frontend: javascript
        framework: react
extensions:
  amplify:
