AWSTemplateFormatVersion: "2010-09-09"
Description: WAF Configuration for CloudFront and AppSync

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Stage name for resource naming

Resources:
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub nlmonorepo-waf-${Stage}
      Description: WAF Web ACL for CloudFront and AppSync
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub nlmonorepo-waf-${Stage}
      Rules:
        - Name: RateLimit
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimit
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSetMetric
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesKnownBadInputsRuleSetMetric

Outputs:
  WebACLId:
    Description: Web ACL ID
    Value: !GetAtt WAFWebACL.Id
    Export:
      Name: !Sub nlmonorepo-waf-${Stage}-web-acl-id
  WebACLArn:
    Description: Web ACL ARN
    Value: !GetAtt WAFWebACL.Arn
    Export:
      Name: !Sub nlmonorepo-waf-${Stage}-web-acl-arn
