Resources:

  cwlDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
        - AttributeName: "fieldName"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: fieldName
          KeyType: RANGE
      Tags:
        - Key: Name
          Value: cwlDataTable
      SSESpecification:
        SSEEnabled: true
      StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

