Resources:
  CWLCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        WebACLId: ${env:CloudFrontWAFArn}
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt CWLBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CWLCloudFrontOAC.Id
        Enabled: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /404.html
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt CloudfrontRedirectFn.FunctionMetadata.FunctionARN
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ResponseHeadersPolicyId: !Ref CWLCloudfFrontResponseHeadersPolicy
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  CWLCloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: cwl-cloudfront-oac-${opt:stage}
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # this is needed to have sub directory working properly
  # since we're changing from public s3 with web hosting + cloudfront
  # to private s3 + cloudfront + OriginAccessControl (OAC)
  # which loses the web hosting feature of auto append /index.html to sub directories
  CloudfrontRedirectFn:
    Type: AWS::CloudFront::Function
    Properties:
      Name: cwl-cloudfront-redirect-fn-${opt:stage}
      AutoPublish: true
      FunctionCode: !Sub |
        function handler(event) {
          var request = event.request;
          var uri = request.uri;
          if (!uri) {
            return request;
          }
          if (uri.endsWith("/")) {
            request.uri += "index.html";
          } else if (!uri.includes(".")) {
            request.uri += "/index.html";
          }
          return request;
        }
      FunctionConfig:
        Comment: "Function to append /index.html to URIs"
        Runtime: "cloudfront-js-1.0"

  CWLCloudfFrontResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: "CWLCloudfFrontResponseHeadersPolicy"
        CustomHeadersConfig:
            Items:
              - Header: Permissions-Policy
                Value: "geolocation=(self), microphone=()"
                Override: true

        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000 # 1 year
            IncludeSubdomains: true
            Override: true
            Preload: true

          FrameOptions:
            FrameOption: DENY
            Override: true

          ContentTypeOptions:
            Override: true

          ReferrerPolicy:
            ReferrerPolicy: no-referrer
            Override: true

          ContentSecurityPolicy:
            # use !Join function to break CSP into multiple lines for better readability
            ContentSecurityPolicy: !Join
            - ""
            - - "default-src 'self'"
              - "; "
              - "frame-src 'self' blob:"
              - "; "
              - "frame-ancestors 'self'"
              - "; "
              - "script-src 'self' 'unsafe-eval'"
              - "; "
              - "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com"
              - "; "
              - "font-src 'self' data: https://fonts.googleapis.com https://fonts.gstatic.com"
              - "; "
              - "img-src 'self' data: https://cwl-user-files-${opt:stage}.s3.ap-southeast-2.amazonaws.com"
              - ";"
              - "connect-src 'self' "
              - "https://cognito-idp.ap-southeast-2.amazonaws.com "
              - "https://cognito-identity.ap-southeast-2.amazonaws.com "
              - !Sub "${GraphQlApi.GraphQLUrl} "
              # iconify
              - "https://api.iconify.design https://api.simplesvg.com https://api.unisvg.com "
              - "https://fonts.googleapis.com https://fonts.gstatic.com "
              - "data:"
              - ";"
            Override: true
