org: transfigr
app: fta-mono-repo
service: pfh-waf

configValidationMode: error

frameworkVersion: "3"

outputs:
  CloudFrontWAFArn: !GetAtt PFHWAF.Arn

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage}

resources:
  Resources:
    PFHWAF:
      Type: "AWS::WAFv2::WebACL"
      Properties:
        Name: PFHWAF
        Scope: CLOUDFRONT
        DefaultAction:
          Allow: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: myWAFMetric
        Rules:
          - Name: AWSManagedCommonRuleSet
            Priority: 1
            OverrideAction:
              None: {}
            Statement:
              ManagedRuleGroupStatement:
                VendorName: AWS
                Name: AWSManagedRulesCommonRuleSet
            VisibilityConfig:
              SampledRequestsEnabled: true
              CloudWatchMetricsEnabled: true
              MetricName: AWSManagedCommonRuleSetMetric
 