AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Live DynamoDB Resources'

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    AllowedPattern: ^[a-zA-Z0-9-]+$

Resources:
  # Data Table
  cwlDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
        - AttributeName: "fieldName"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: fieldName
          KeyType: RANGE
      Tags:
        - Key: Name
          Value: cwlDataTable
      SSESpecification:
        SSEEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  CWLDataTableName:
    Value: !Ref cwlDataTable
    Description: Name of the CloudWatchLive data table
  
  CWLDataTableArn:
    Value: !GetAtt cwlDataTable.Arn
    Description: ARN of the CloudWatchLive data table
