projects:
  Codegen Project:
    schemaPath: combined_schema.graphql
    includes:
      - src/graphql/**/*.ts
      - src/graphql/**/*.tsx # Restore this line
      - src/graphql/**/mutations.ts # Restore this line
      # - ../../shared/types/**/*.graphql # Keep this commented out
    excludes:
      - ./amplify/**
      - src/types/gqlTypes.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/types/gqlTypes.ts
        frontend: javascript
        framework: react
extensions:
  amplify:
    version: 3
