AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Live S3 Resources'

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    AllowedPattern: ^[a-zA-Z0-9-]+$

Resources:
  # S3 Bucket for storing nextjs/react app
  CWLBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "nlmonorepo-cwl-userfiles-${Stage}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  CWLBucketName:
    Value: !Ref CWLBucket
    Description: Name of the CloudWatchLive bucket
  
  CWLBucketArn:
    Value: !GetAtt CWLBucket.Arn
    Description: ARN of the CloudWatchLive bucket
    
  CWLBucketRegionalDomainName:
    Value: !GetAtt CWLBucket.RegionalDomainName
    Description: Regional domain name of the CloudWatchLive bucket
