AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFront Resources for Application"

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    AllowedPattern: ^[a-zA-Z0-9-]+$
  AppName:
    Type: String
    Description: Application Name (e.g., awse, wbc)
  AppBucketName: # Renamed from AWSEBucketName
    Type: String
    Description: Name of the S3 bucket for CloudFront origin
  AppBucketArn: # Renamed from AWSEBucketArn
    Type: String
    Description: ARN of the S3 bucket for CloudFront origin
  AppBucketRegionalDomainName: # Renamed from AWSEBucketRegionalDomainName
    Type: String
    Description: Regional domain name of the S3 bucket for CloudFront origin

Resources:
  AppBucketPolicy: # Renamed from AWSEBucketPolicy
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref AppBucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Ref AppBucketArn
              - !Sub "${AppBucketArn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${AppCloudFrontDistribution}"

  AppCloudFrontOAC: # Renamed from AWSECloudFrontOAC
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AppName}BucketOAC"
        Description: "Origin Access Control for application bucket"
        SigningBehavior: always
        SigningProtocol: sigv4
        OriginAccessControlOriginType: s3

  AppCloudFrontDistribution: # Renamed from AWSECloudFrontDistribution
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub "CloudFront distribution for ${AppName} ${Stage}"
        Origins:
          - DomainName: !Ref AppBucketRegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: "" # Required to be empty when using OAC
            OriginAccessControlId: !GetAtt AppCloudFrontOAC.Id
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # CORS-S3Origin

Outputs:
  AWSECloudFrontDistributionId:
    Description: "ID of the CloudFront distribution"
    Value: !Ref AppCloudFrontDistribution
    # Export removed: top-level template will declare global export

  AWSECloudFrontDomainName:
    Description: "Domain name of the CloudFront distribution"
    Value: !GetAtt AppCloudFrontDistribution.DomainName
    # Export removed: top-level template will declare global export
