Parameters:
  Stage:
    Type: String
    Description: Deployment stage
  KMSKeyArn:
    Type: String
    Description: ARN of the KMS key for encryption

Resources:
  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub nl-mono-repo-dynamodb-${Stage}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:user/nlmonorepo-shared-dev
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBTableManagement
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !Ref KMSKeyArn

  cwlUserTable:
    Type: AWS::DynamoDB::Table
    DependsOn: DynamoDBRole
    Properties:
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      Tags:
        - Key: Name
          Value: cwlUserTable
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref KMSKeyArn
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  cwlUserTableName:
    Value: !Ref cwlUserTable
    Export:
      Name: !Sub cwlUserTableName-${Stage}
  cwlUserTableArn:
    Value: !GetAtt cwlUserTable.Arn
    Export:
      Name: !Sub cwlUserTableArn-${Stage}

