AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Live Backend Infrastructure'

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    AllowedPattern: ^[a-zA-Z0-9-]+$
  TemplateBucketName:
    Type: String
    Description: Name of the S3 bucket containing nested stack templates
  KMSKeyId:
    Type: String
    Description: KMS Key ID for encryption
  KMSKeyArn:
    Type: String
    Description: KMS Key ARN for encryption
  WebACLId:
    Type: String
    Description: WAF Web ACL ID from us-east-1 region
  WebACLArn:
    Type: String
    Description: WAF Web ACL ARN from us-east-1 region

Resources:
  # DynamoDb Tables
  DynamoDbStack:
  # DynamoDb Tables
  DynamoDbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/resources/DynamoDb/dynamodb.yaml
      Parameters:
        Stage: !Ref Stage
        KMSKeyArn: !Ref KMSKeyArn

  # S3 Buckets for frontend and assets
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/resources/S3/s3.yaml
      Parameters:
        Stage: !Ref Stage
        KMSKeyId: !Ref KMSKeyId

  # CloudFront Distribution
  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/resources/CloudFront/cloudfront.yaml
      Parameters:
        Stage: !Ref Stage
        WebACLId: !Ref WebACLId
        WebACLArn: !Ref WebACLArn
        CWLBucketName: !GetAtt S3Stack.Outputs.CWLBucketName
        CWLBucketArn: !GetAtt S3Stack.Outputs.CWLBucketArn
        CWLBucketRegionalDomainName: !GetAtt S3Stack.Outputs.CWLBucketRegionalDomainName

  # AppSync API
  AppSyncStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [DynamoDbStack, CloudFrontStack]
    DependsOn: [DynamoDbStack, CloudFrontStack]
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/resources/AppSync/appSync.yaml
      Parameters:
        Stage: !Ref Stage
        TemplateBucketName: !Ref TemplateBucketName

  # Lambda Functions
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [DynamoDbStack, AppSyncStack, CloudFrontStack]
    DependsOn: [DynamoDbStack, AppSyncStack, CloudFrontStack]
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/resources/Lambda/lambda.yaml
      Parameters:
        Stage: !Ref Stage
        TemplateBucketName: !Ref TemplateBucketName
        CWLCloudFrontDistributionId: !GetAtt CloudFrontStack.Outputs.CWLCloudFrontDistributionId
        CWLCloudFrontDomainName: !GetAtt CloudFrontStack.Outputs.CWLCloudFrontDomainName

Outputs:
  ApiUrl:
    Description: AppSync API URL
    Value: !GetAtt AppSyncStack.Outputs.CWLAppSyncApiUrl
    Value: !GetAtt AppSyncStack.Outputs.CWLAppSyncApiUrl
    Export:
      Name: !Sub nlmonorepo-cwl-${Stage}-api-url

  ApiId:
    Description: AppSync API ID
    Value: !GetAtt AppSyncStack.Outputs.CWLAppSyncApiId
    Value: !GetAtt AppSyncStack.Outputs.CWLAppSyncApiId
    Export:
      Name: !Sub nlmonorepo-cwl-${Stage}-api-id

  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontStack.Outputs.CWLCloudFrontDomainName
    Export:
      Name: !Sub nlmonorepo-cwl-${Stage}-cloudfront-domain

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !GetAtt CloudFrontStack.Outputs.CWLCloudFrontDistributionId
    Export:
      Name: !Sub nlmonorepo-cwl-${Stage}-cloudfront-id

  WebsiteBucket:
    Description: S3 bucket for frontend website assets
    Description: S3 bucket for frontend website assets
    Value: !GetAtt S3Stack.Outputs.CWLBucketName
    Export:
      Name: !Sub nlmonorepo-cwl-${Stage}-website-bucket
