AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Live Backend Infrastructure'

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    AllowedPattern: ^[a-zA-Z0-9-]+$
  TemplateBucketName:
    Type: String
    Description: Name of the S3 bucket containing nested stack templates
  KMSKeyId:
    Type: String
    Description: KMS Key ID for encryption
  KMSKeyArn:
    Type: String
    Description: KMS Key ARN for encryption
  WebACLId:
    Type: String
    Description: WAF Web ACL ID from us-east-1 region
  WebACLArn:
    Type: String
    Description: WAF Web ACL ARN from us-east-1 region

Resources:
  # DynamoDb Tables
  DynamoDbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/resources/DynamoDb/dynamoDb.yaml
      Parameters:
        Stage: !Ref Stage
        AppName: cwl
        KMSKeyArn: !Ref KMSKeyArn

  # S3 Buckets for frontend and assets
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/resources/S3/s3.yaml
      Parameters:
        Stage: !Ref Stage
        KMSKeyId: !Ref KMSKeyId

  # Cognito Resources
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/resources/Cognito/cognito.yaml
      Parameters:
        Stage: !Ref Stage

  # CloudFront Distribution
  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3Stack
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/resources/CloudFront/cloudfront.yaml
      Parameters:
        Stage: !Ref Stage
        AppName: cwl
        AppBucketName: !GetAtt S3Stack.Outputs.CWLBucketName
        AppBucketArn: !GetAtt S3Stack.Outputs.CWLBucketArn
        AppBucketRegionalDomainName: !GetAtt S3Stack.Outputs.CWLBucketRegionalDomainName

  # Lambda Functions
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [CloudFrontStack, CognitoStack]
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/resources/Lambda/lambda.yaml
      Parameters:
        Stage: !Ref Stage
        AppName: cwl
        AppCloudFrontDistributionId: !GetAtt CloudFrontStack.Outputs.CWLCloudFrontDistributionId
        AppCloudFrontDomainName: !GetAtt CloudFrontStack.Outputs.CWLCloudFrontDomainName
        FromEmail: noreply@cloudwatchlive.com
        AppURL: !Sub "https://${CloudFrontStack.Outputs.CWLCloudFrontDomainName}"
        TemplateBucketName: !Ref TemplateBucketName
        UserPoolId: !GetAtt CognitoStack.Outputs.UserPoolId

  # AppSync API
  AppSyncStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [DynamoDbStack, CognitoStack, LambdaStack]
    Properties:
      TemplateURL: !Sub https://${TemplateBucketName}.s3.${AWS::Region}.amazonaws.com/resources/AppSync/appsync.yaml
      Parameters:
        Stage: !Ref Stage
        AppName: cwl
        TemplateBucketName: !Ref TemplateBucketName
        UserPoolId: !GetAtt CognitoStack.Outputs.UserPoolId
        SendWelcomeEmailFunctionArn: !GetAtt LambdaStack.Outputs.SendWelcomeEmailFunctionArn
        CreateCognitoUserFunctionArn: !GetAtt LambdaStack.Outputs.CreateCognitoUserFunctionArn

Outputs:
  ApiUrl:
    Description: AppSync API URL
    Value: !GetAtt AppSyncStack.Outputs.CWLAppSyncApiUrl
    Export:
      Name: !Sub nlmonorepo-cwl-${Stage}-api-url

  ApiId:
    Description: AppSync API ID
    Value: !GetAtt AppSyncStack.Outputs.CWLAppSyncApiId
    Export:
      Name: !Sub nlmonorepo-cwl-${Stage}-api-id
      
  CWLUserPoolId:
    Description: "Cognito User Pool ID for CWL"
    Value: !GetAtt CognitoStack.Outputs.UserPoolId
    Export:
      Name: !Sub "nlmonorepo-cwl-${Stage}-user-pool-id"

  CWLUserPoolClientId:
    Description: "Cognito User Pool Client ID for CWL"
    Value: !GetAtt CognitoStack.Outputs.UserPoolClientId
    Export:
      Name: !Sub "nlmonorepo-cwl-${Stage}-user-pool-client-id"

  CWLIdentityPoolId:
    Description: "Cognito Identity Pool ID for CWL"
    Value: !GetAtt CognitoStack.Outputs.IdentityPoolId
    Export:
      Name: !Sub "nlmonorepo-cwl-${Stage}-identity-pool-id"

  WebsiteBucket:
    Description: "S3 bucket for frontend website assets"
    Value: !GetAtt S3Stack.Outputs.CWLBucketName
    Export:
      Name: !Sub "nlmonorepo-cwl-${Stage}-website-bucket"

  CloudFrontDistributionId:
    Description: "CloudFront Distribution ID"
    Value: !GetAtt CloudFrontStack.Outputs.CWLCloudFrontDistributionId
    Export:
      Name: !Sub "nlmonorepo-cwl-${Stage}-cloudfront-id"

  CloudFrontDomainName:
    Description: "CloudFront Distribution Domain Name"
    Value: !GetAtt CloudFrontStack.Outputs.CWLCloudFrontDomainName
    Export:
      Name: !Sub "nlmonorepo-cwl-${Stage}-cloudfront-domain"
