Parameters:
    Stage:
      Type: String
      Description: Deployment stage
    KMSKeyId:
      Type: String
      Description: KMS Key ID for bucket encryption
    KMSKeyArn:
      Type: String
      Description: KMS Key ARN for bucket encryption

Resources:
    S3Role:
      Type: AWS::IAM::Role
      Properties:
        RoleName: !Sub nlmonorepo-s3-${Stage}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS: !Sub arn:aws:iam::${AWS::AccountId}:user/nlmonorepo-shared-${Stage}
                Service: cloudformation.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: S3Management
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:*
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - kms:Decrypt
                    - kms:GenerateDataKey
                  Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${KMSKeyId}

# User files bucket moved to CloudWatch Live package

Outputs:
    SharedStackDeployed:
      Description: "Indicates that the S3 stack was deployed"
      Value: true
