AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Live S3 Resources'

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    AllowedPattern: ^[a-zA-Z0-9-]+$
  KMSKeyId:
    Type: String
    Description: KMS Key ID for bucket encryption (optional)
    Default: ""

Resources:
  # S3 Bucket for storing nextjs/react app
  CWLBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "nlmonorepo-cwl-userfiles-${Stage}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasKMSKey, aws:kms, AES256]
              KMSMasterKeyID: !If [HasKMSKey, !Ref KMSKeyId, !Ref "AWS::NoValue"]
            BucketKeyEnabled: true

Conditions:
  HasKMSKey: !Not [!Equals [!Ref KMSKeyId, ""]]

Outputs:
  CWLBucketName:
    Value: !Ref CWLBucket
    Description: Name of the CloudWatchLive bucket
    Export:
      Name: !Sub "cwlUserFilesBucketName-${Stage}"
  
  CWLBucketArn:
    Value: !GetAtt CWLBucket.Arn
    Description: ARN of the CloudWatchLive bucket
    Export:
      Name: !Sub "cwlUserFilesBucketArn-${Stage}"
    
  CWLBucketRegionalDomainName:
    Value: !GetAtt CWLBucket.RegionalDomainName
    Description: Regional domain name of the CloudWatchLive bucket
    Export:
      Name: !Sub "cwlUserFilesBucketRegionalDomainName-${Stage}"
