AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Live S3 Resources'

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    AllowedPattern: ^[a-zA-Z0-9-]+$
  KMSKeyId:
    Type: String
    Description: KMS Key ID for bucket encryption (optional)
    Default: ""

Resources:
  # S3 Bucket for storing nextjs/react app
  CWLFrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "nlmonorepo-cwl-frontend-${Stage}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [HasKMSKey, aws:kms, AES256]
              KMSMasterKeyID: !If [HasKMSKey, !Ref KMSKeyId, !Ref "AWS::NoValue"]
            BucketKeyEnabled: true

Conditions:
  HasKMSKey: !Not [!Equals [!Ref KMSKeyId, ""]]

Outputs:
  CWLBucketName:
    Value: !Ref CWLFrontendBucket
    Description: Name of the CloudWatchLive frontend bucket
    Export:
      Name: !Sub "cwlFrontendBucketName-${Stage}"
  
  CWLBucketArn:
    Value: !GetAtt CWLFrontendBucket.Arn
    Description: ARN of the CloudWatchLive frontend bucket
    Export:
      Name: !Sub "cwlFrontendBucketArn-${Stage}"
    
  CWLBucketRegionalDomainName:
    Value: !GetAtt CWLFrontendBucket.RegionalDomainName
    Description: Regional domain name of the CloudWatchLive frontend bucket
    Export:
      Name: !Sub "cwlFrontendBucketRegionalDomainName-${Stage}"
