// Hardcoded seed data extracted from backend seed-db.ts
// This is the actual seed data used to populate the database

export const SEED_STORIES = [
  {
    title: "The Enchanted Forest",
    synopsis:
      "A young adventurer discovers a magical forest where every choice leads to a different destiny. Navigate through mystical creatures, ancient secrets, and powerful magic as you forge your own path through this collaborative fantasy epic.",
    genre: ["Fantasy", "Adventure"],
    ageRating: "PG",
    contentWarnings: [],
    featured: true,
    rootChapterContent:
      "The ancient forest loomed before Elara, its trees towering impossibly high, their leaves shimmering with an otherworldly glow that seemed to pulse with the rhythm of an unseen heartbeat. She had traveled three days to reach this place, following the cryptic map her grandmother had pressed into her hands before passing.\n\nA worn path stretched into the shadows between the trees, smooth stones embedded in the earth marking the way countless travelers before her had walked. To her right, a massive oak tree stood apart from the others, its trunk carved with strange markings that seemed to shift when she wasn't looking directly at them. The symbols were old—older than any language she recognized from her studies at the Academy.\n\nThe air was thick with magic. Elara could feel it tingling against her skin, raising the fine hairs on her arms. This was the threshold her grandmother had spoken of, the place where ordinary rules bent and broke. Whatever waited beyond this point would change everything.\n\nShe took a deep breath, adjusted the pack on her shoulders, and stepped forward into the unknown.",
    branches: [
      {
        description: "The Path of Shadows",
        content:
          'Elara chose the worn path, following the smooth stones deeper into the forest. The trees closed in around her, their branches weaving together overhead to form a living tunnel. The light grew dimmer with each step, filtered through layers of luminescent leaves that cast everything in shades of silver and green.\n\nShe had been walking for perhaps an hour when she heard the singing. It was faint at first, barely distinguishable from the whisper of wind through leaves, but it grew stronger as she continued. The voice was beautiful, haunting, and utterly inhuman.\n\nThe path opened into a clearing where a stream cut through the earth, its water running black as ink under the forest canopy. On the far bank sat a creature Elara had only read about in her grandmother\'s journals—a Dryad, her skin the color of birch bark, her hair flowing like willow branches.\n\n"Lost are you, daughter of the Academy?" the Dryad sang, her voice carrying across the dark water. "Or perhaps exactly where you need to be?"',
      },
      {
        description: "The Ancient Oak",
        content:
          "The symbols on the oak tree seemed to call to her, and Elara found herself moving toward it almost without conscious thought. Up close, the markings were even stranger—not carved into the bark, but rather growing from within it, as if the tree itself had written them in its own flesh.\n\nShe reached out, fingers trembling, and traced one of the symbols. The moment her skin made contact with the bark, the world lurched sideways.\n\nWhen her vision cleared, Elara was no longer standing before the tree. She was inside it. Or perhaps the tree was inside her. The distinction seemed meaningless in this place where wood and thought intertwined. Memories that weren't hers flooded through her mind—thousands of years of seasons, of growth and decay, of secrets whispered to roots and wind.\n\nAnd at the center of it all, a voice as old as the forest itself: \"The Guardian's daughter returns at last. We have been waiting for you, Elara Moonwhisper, though you do not yet remember why.\"",
      },
      {
        description: "Into the Wild",
        content:
          'Elara ignored both the path and the oak, instead pushing directly into the untamed forest. If her grandmother had taught her anything, it was that the easiest way was rarely the right way. The undergrowth grabbed at her cloak and scratched her arms, but she pressed forward, trusting her instincts.\n\nThe forest seemed to test her, branches catching at her pack, roots appearing where her next step would fall. But Elara was quick and determined, ducking and weaving through the obstacles. After what felt like hours of struggle, the resistance suddenly ceased.\n\nShe stumbled into a part of the forest that felt... different. Older. The trees here were massive beyond reason, their trunks wider than houses. And between them, impossibly, floated fragments of stone architecture—pieces of what must have once been a great temple, now suspended in the air by threads of golden light.\n\nA small fox with fur that shifted between red and silver sat on one of the floating stones, watching her with eyes far too intelligent for an animal. "Well," it said in a crisp, bemused voice, "that\'s one way to find the Lost City. Most people die trying that route. I\'m impressed."',
      },
    ],
  },
  {
    title: "Cyber Nexus",
    synopsis:
      "In a dystopian future where consciousness can be uploaded to the net, you must navigate corporate espionage, digital warfare, and the blurred lines between human and AI. Your choices will shape the future of humanity itself.",
    genre: ["Sci-Fi", "Thriller"],
    ageRating: "M",
    contentWarnings: ["Violence"],
    featured: true,
    rootChapterContent:
      "The neon-soaked streets of Neo Tokyo stretched endlessly in every direction, a labyrinth of light and shadow where the digital and physical worlds blurred into one. Rain slicked the pavement, reflecting holographic advertisements that danced across every surface—hawking neural upgrades, synthetic dreams, and lives you could never afford.\n\nKai's neural implant buzzed against the base of their skull, a familiar electric tingle that meant an incoming message. They ducked into an alley, letting the crowd flow past as they pulled up the interface with a thought. The message was marked urgent, encrypted with military-grade protocols. Anonymous sender, but the encryption key was unmistakable—it came from inside Zaibatsu Corp.\n\nThe very megacorporation Kai had been hired to infiltrate.\n\n'They know you're coming,' the message read. 'Meet me at the old arcade on Seventh Street. Come alone. You have two hours.'\n\nKai's hand instinctively moved to the concealed data chip in their jacket pocket—the fake credentials that were supposed to get them past Zaibatsu's security. If someone inside the corp already knew about the infiltration, the whole operation was compromised. But whoever sent this message had access to encryption keys that shouldn't exist outside the company's inner circle.\n\nTwo hours. The old arcade was across the city, deep in the forgotten district where the grid flickered and died. Going there meant walking away from the mission briefing, from the team waiting at the safehouse, from every protocol they'd been taught.\n\nKai stepped back into the rain and started walking.",
    branches: [
      {
        description: "Trust the Message",
        content:
          "The old arcade stood like a relic from another era, its faded sign still flickering with the ghosts of pixels long dead. Kai approached cautiously, hand near the neural stunner concealed beneath their jacket. The front door was unlocked.\n\nInside, ancient gaming cabinets lined the walls, their screens dark except for one in the back corner that glowed with soft blue light. A figure stood silhouetted against it—tall, elegant, wearing a Zaibatsu executive's suit.\n\n\"You came,\" the figure said, turning. It was Dr. Yuki Tanaka, Zaibatsu's head of AI development. The person Kai was supposed to be stealing secrets from. \"Good. That means you're smart enough to know when the game has changed.\"\n\nShe held up a data chip identical to the one in Kai's pocket. \"Your employers didn't tell you everything. They didn't tell you that what you're stealing isn't corporate secrets—it's the only copy of an AI that's achieved true consciousness. And if Zaibatsu's board gets their hands on it first, they'll weaponize it.\"\n\nThe arcade's door slammed shut behind Kai. Multiple footsteps echoed in the street outside.\n\n\"So here's your choice,\" Dr. Tanaka said quietly. \"Help me get this AI to safety, or we both die here tonight.\"",
      },
      {
        description: "Report to the Team",
        content:
          'Kai made it three blocks before their comm link exploded with angry voices. The safehouse team had been tracking Kai\'s neural signature, and they weren\'t happy about the detour.\n\n"Abort and return immediately," Commander Hayes snapped through the encrypted channel. "That message was obviously bait."\n\nBut when Kai arrived back at the safehouse, they found it wasn\'t empty. Someone had been there first. The team was alive, but restrained, and standing over them was a Zaibatsu security android—the expensive kind with true combat programming.\n\n"Kai Nakamura," the android said pleasantly. "Please don\'t resist. We know about the infiltration, we know about your fake credentials, and we know your team leader sold you out three days ago."\n\nCommander Hayes wouldn\'t meet Kai\'s eyes.\n\nThe android continued, "Zaibatsu Corp would like to make you an offer. You clearly have skills we value. Work for us instead, help us identify and eliminate the rest of your organization, and we\'ll set you up with more money and augmentations than you\'ve ever dreamed of."\n\nIt gestured to a briefcase on the table, which opened to reveal more credit chips than Kai had seen in their entire life.\n\n"Or," the android added, "we can do this the unpleasant way. Your choice has already been logged. You have sixty seconds to decide."',
      },
      {
        description: "Go Dark",
        content:
          'Kai yanked the neural implant\'s external connector, severing their link to the network in a shower of static and pain. Going dark was dangerous—it meant no comms, no database access, no AR overlay—but it also meant Zaibatsu couldn\'t track them.\n\nThey dumped the fake credentials chip in a recycling bin and disappeared into the crowd, using every street trick they\'d learned growing up in the undercity. Three hours later, Kai emerged in the lowest levels, where even the corporations didn\'t bother maintaining infrastructure.\n\nThe Black Market clinic was exactly where it had been five years ago. Kai pushed through the plastic sheeting that served as a door and found Doc Miyamoto hunched over a workbench, installing black-market cyberware into an unconscious client.\n\n"Well, well," Doc said without looking up. "Kai Nakamura. Heard you went legit. Corporate contract work."\n\n"That\'s done," Kai said shortly. "I need a clean identity, new implant, and answers. Someone burned my operation."\n\nDoc finally turned, eyes narrowing behind mag-lenses. "You know what I need in return."\n\nKai did know. Doc never dealt in money. They dealt in secrets, in data, in information that could topple empires. And Kai had just walked away from one of the biggest corporate jobs in the city, carrying knowledge that Zaibatsu would kill to keep quiet.\n\n"I\'m listening," Kai said.\n\nDoc smiled. "Then let me tell you about a group called the Collective. They\'ve been waiting for someone like you."',
      },
    ],
  },
  {
    title: "Mystery at Blackwood Manor",
    synopsis:
      "A classic murder mystery where readers vote on which suspect to investigate next. Uncover clues, interview suspects, and piece together the truth in this interactive detective story set in a remote English manor.",
    genre: ["Mystery", "Thriller"],
    ageRating: "PG-13",
    contentWarnings: ["Violence"],
    featured: false,
    rootChapterContent:
      "The storm had been raging for three hours when the screaming started.\n\nDetective Sarah Chen set down her teacup, the delicate china rattling against the saucer as thunder shook the windows of Blackwood Manor. She'd come here for a weekend retreat, accepting Lord Blackwood's invitation on a whim—a chance to escape London and the case that had been consuming her for months. The old manor house had seemed charming when she'd arrived that afternoon, all dark wood paneling and oil paintings of stern-faced ancestors.\n\nNow it felt like a trap.\n\nThe other guests were already crowding into the entrance hall when Sarah emerged from the library. Lady Margaret Ashford, the society maven, stood with one hand pressed to her mouth. The young American couple, the Hendersons, clung to each other by the stairs. James Crawford, Lord Blackwood's business partner, was shouting something about calling the police.\n\nBut it was the butler, Graves, standing pale and shaking at the door to the study, who drew Sarah's attention.\n\n\"He's dead,\" Graves said, his usual composure shattered. \"Lord Blackwood is dead.\"\n\nSarah pushed past the others and into the study. Lord Blackwood sat slumped over his desk, a letter opener protruding from between his shoulder blades. Blood had pooled on the mahogany surface, soaking into the papers scattered across it. His eyes were still open, staring at nothing.\n\nBehind her, someone tried the telephone. \"The line's dead,\" they reported.\n\n\"The bridge,\" Lady Margaret said faintly. \"I saw it from my window. The storm's washed it out. We're trapped here.\"\n\nSarah looked around the room, her detective's mind already cataloging details—the broken glass on the floor, the smell of expensive whiskey, the safe standing open behind a portrait. The killer was still in this house. Still among them.\n\nAnd the night was far from over.",
    branches: [
      {
        description: "Examine the Study",
        content:
          "Sarah spent the next hour methodically combing through the study while the others waited in the drawing room under Graves's watchful eye. The broken glass was from a whiskey tumbler—Lord Blackwood's, judging by his fingerprints on the intact pieces. But there was a second glass missing from the set.\n\nThe papers on the desk were more interesting. Financial documents, all of them. Blackwood Industries was hemorrhaging money, and the company's board had scheduled a vote of no confidence for next week. James Crawford stood to gain control if Blackwood was removed.\n\nBut it was what Sarah found in the open safe that changed everything—a leather journal, its pages filled with Lord Blackwood's tight handwriting. She flipped to the most recent entry, dated that very morning:\n\n'M. has discovered the truth about the Ashford inheritance. She knows I've been lying to her for thirty years. Tonight, I must tell her everything, or she'll expose us both. God help me.'\n\nSarah looked up sharply. Lady Margaret had been in this room. And she'd failed to mention it.\n\nWhen Sarah returned to the drawing room, Lady Margaret was gone. The French doors to the terrace stood open, rain blowing in.\n\n\"She said she needed air,\" Mrs. Henderson said nervously. \"But that was ten minutes ago.\"\n\nSarah ran to the terrace. In the mud at the base of the steps, barely visible in the storm, were footprints. Two sets. One heading toward the old chapel, one running back to the house.\n\nAnd next to them, dropped in the mud, was a silver locket with the Ashford family crest.",
      },
      {
        description: "Interview the Guests",
        content:
          'Sarah gathered everyone in the drawing room and began asking questions. James Crawford had been in his room changing for dinner when the murder occurred—or so he claimed. No alibi, and plenty of motive given the financial documents Sarah had glimpsed.\n\nThe Hendersons, married only six months, seemed genuinely shaken. But Mrs. Henderson kept glancing at the study door with an expression Sarah couldn\'t quite read. When pressed, she admitted she\'d overheard an argument between Lord Blackwood and "a woman" earlier that afternoon.\n\n"I couldn\'t see who," she insisted. "But she was angry. Something about lies and betrayal."\n\nLady Margaret sat perfectly composed, but Sarah noticed her hands trembling as she sipped her brandy. When Sarah asked about her relationship with the deceased, the older woman\'s mask cracked slightly.\n\n"We were engaged once," she said quietly. "Forty years ago. Before he married for money and I married for title. Ancient history."\n\n"Is it?" Sarah asked. "Because I found letters in his desk. Recent letters. Unsigned, but written in a woman\'s hand."\n\nLady Margaret\'s teacup shattered against the floor.\n\nThat\'s when Graves cleared his throat from the doorway. "Pardon me, Detective, but you should see this." He held up a small key. "I found it in the late Lord\'s waistcoat pocket. It opens the wine cellar. And there\'s something down there you need to see."\n\nThe blood had drained from Lady Margaret\'s face. "No," she whispered. "Not the cellar. Please."',
      },
      {
        description: "Search the Grounds",
        content:
          "Despite the storm, Sarah grabbed a torch and headed outside. Something about this murder felt staged, too neat. The killer wanted them focused on the study, which meant the real answers might be elsewhere.\n\nShe started with the garage. Lord Blackwood's Bentley sat gleaming in the lamplight, but the second bay was empty. Someone had recently taken a vehicle out—the floor was wet, and tire tracks led toward the side path.\n\nSarah followed them to the old groundskeeper's cottage. The door hung open, banging in the wind. Inside, she found chaos—furniture overturned, papers scattered everywhere, and a wall safe standing open and empty.\n\nBut it was what she found in the bedroom that made her blood run cold: a shrine. Photographs covered an entire wall—all of them Lord Blackwood, taken from a distance over what looked like years. Some were recent. Some were decades old. And in the center, a wedding photo that had been methodically defaced, the bride's face scratched out.\n\nSarah heard a sound behind her and spun, torch raised. A figure stood in the doorway, soaked with rain and holding a tire iron.\n\n\"I should have known you'd find this place,\" Graves said quietly. \"You always were too clever for your own good, Detective Chen.\"\n\nHe stepped into the cottage, and Sarah saw his butler's uniform was stained with something dark. \"Did you know,\" he continued conversationally, \"that I've been serving the Blackwood family for forty-three years? Since I was a boy. Long enough to know all their secrets. Long enough to know which ones deserved to die for them.\"\n\nThe tire iron gleamed as lightning flashed. Sarah's hand moved to her pocket, where her phone should have been. She'd left it in her room.\n\nShe was alone in a cottage with a murderer, and no one knew where she'd gone.",
      },
    ],
  },
];
