AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Live DynamoDB Resources'

Parameters:
  Stage:
    Type: String
    Description: Deployment stage (e.g., dev, prod)
    AllowedPattern: ^[a-zA-Z0-9-]+$
  KMSKeyArn:
    Type: String
    Description: ARN of KMS key for DynamoDB encryption
    Default: ""

Resources:
  # Data Table
  cwlDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "nlmonorepo-cwl-usertable-${Stage}"
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      Tags:
        - Key: Name
          Value: cwlDataTable
      SSESpecification:
        SSEEnabled: true
        SSEType: !If [HasKMSKey, "KMS", "AES256"] 
        KMSMasterKeyId: !If [HasKMSKey, !Ref KMSKeyArn, !Ref "AWS::NoValue"]
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Conditions:
  HasKMSKey: !Not [!Equals [!Ref KMSKeyArn, ""]]

Outputs:
  CWLDataTableName:
    Value: !Ref cwlDataTable
    Description: Name of the CloudWatchLive data table
    Export:
      Name: !Sub "cwlUserTableName-${Stage}"
  
  CWLDataTableArn:
    Value: !GetAtt cwlDataTable.Arn
    Description: ARN of the CloudWatchLive data table
    Export:
      Name: !Sub "cwlUserTableArn-${Stage}"
