Parameters:
  Stage:
    Type: String
    Description: Deployment stage
  AppName:
    Type: String
    Description: Application Name
    Default: cwl
  # KMSKeyArn will be passed from the main CWL stack, which gets it from SharedKMSKeyArn output
  KMSKeyArn:
    Type: String
    Description: ARN of the KMS key for encryption

Resources:
  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub nlmonorepo-${AppName}-dynamodb-${Stage}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBTableManagement
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*" # Scope down if possible
              - Effect: Allow # Allow access to the specific KMS key
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey*
                Resource: !Ref KMSKeyArn

  AppSyncDynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub nlmonorepo-${AppName}-appsync-dynamodb-${Stage}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppSyncDynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt CWLDataTable.Arn
                  - !Sub "${CWLDataTable.Arn}/*"
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !Ref KMSKeyArn

  CWLDataTable: # Single-table design for organizations, users, and other entities
    Type: AWS::DynamoDB::Table
    DependsOn: DynamoDBRole
    Properties:
      TableName: !Sub "nlmonorepo-${AppName}-datatable-${Stage}"
      AttributeDefinitions:
        - AttributeName: "PK" # Partition key for single-table design
          AttributeType: "S"
        - AttributeName: "SK" # Sort key for single-table design
          AttributeType: "S"
        - AttributeName: "GSI1PK" # GSI1 partition key for alternate access patterns
          AttributeType: "S"
        - AttributeName: "GSI1SK" # GSI1 sort key for alternate access patterns
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "GSI1"
          KeySchema:
            - AttributeName: "GSI1PK"
              KeyType: "HASH"
            - AttributeName: "GSI1SK"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      Tags:
        - Key: Name
          Value: !Sub "${AppName} DataTable"
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref KMSKeyArn
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES # Adjust as needed

Outputs:
  CWLDataTableName: # Output name expected by parent CWL stack
    Value: !Ref CWLDataTable
    # Export removed: top-level template will declare canonical exports

  CWLDataTableArn: # Output name expected by parent CWL stack
    Value: !GetAtt CWLDataTable.Arn
    # Export removed: top-level template will declare canonical exports

  AppSyncDynamoDBRoleArn: # Added for AppSync DataSource ServiceRoleArn
    Description: ARN of the IAM role for AppSync to access DynamoDB
    Value: !GetAtt AppSyncDynamoDBRole.Arn
    # Export removed: top-level template will declare canonical exports
